server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/library #${JDBC_URL}
    username: postgres #${DB_USERNAME}
    password: postgres #${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-dev-liquibase-run.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      show-sql: true


